### ISSUE TITLE
Build failure on OSX 10.7.1 (autoconf)

### ISSUE THREAD

**Issue by keithj** [irods/externals#1]
I hope I'm using the build system correctly:

```
$ make
./build.py autoconf > autoconf.log
make: *** [irods-externals-autoconf5ad3567c-0-1.0.pkg] Error 2
```

The autoconf.log ends with this:

```
DEBUG: running: ['which', 'fpm'], unsafe_shell=False, check_rc=fpm not found, try "gem install fpm"
DEBUG:   stdout: 
DEBUG:   stderr: 
DEBUG: 
ERROR: fpm not found, try "gem install fpm"
```

Which has me confused because that implies a dependency on Ruby?! Also I'm curious as to why I'm building an experimental version of autoconf? I have autoconf 2.69 installed (via homebrew) and on my PATH. Is that not sufficient to configure these builds?

Thanks.

**Comment by trel** [comment]
Hi Keith,

`fpm` should not be necessary on the mac, we won't be using the packaged versions anyway.  This is fixed in f0978d5.  Pull and you should no longer need `fpm`.

The experimental version of autoconf is referenced in versions.json file comment:

```
        "comment": "ubuntu couldn't build 2.69 due to 8c8522f1 fix coming since",
```
referencing this commit https://github.com/irods/autoconf/commit/8c8522f1 from July, 2012

One of our goals with the new build system is reproducible builds - so keeping things in lockstep across platforms makes attaining this goal much easier.

**Comment by Venustiano** [comment]
Hi

**Following the instructions**

./install_prerequisites.py
make
For CentOS 6, the included compilers are too old to build clang.
After the prerequisites are in place, make sure to use the newly installed g++.

**So far so good, but where is the following file?**

./install_dependencies.py

**Comment by trel** [comment]
mac not actively supported - will open a new issue if necessary.
