### ISSUE TITLE
libcurl deprecated CURLE_SSL_CACERT

### ISSUE THREAD

**Issue by NickHastings** [irods/externals#96]
Hi,

I recently build irods/externals on a Debian 10 system. While doing so I discovered that two of the externals packages: cpr and libs3 seem to need an older version of libcurl than what I have on my system. Both of these packages use the 
now deprecated CURLE_SSL_CACERT.

From the elasticlient.liog:
```
INFO -   stderr: /home/hastings/work/irods/irods-externals/elasticlient0.1.0-1_src/elasticlient/external/httpmockserver/external/cpr/cpr/error.cpp:41:14: fatal error: duplicate case value 'CURLE_PEER_FAILED_VERIFICATION'
        case CURLE_SSL_CACERT:
             ^
/usr/include/x86_64-linux-gnu/curl/curl.h:613:26: note: expanded from macro 'CURLE_SSL_CACERT'
#define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION
                         ^
/home/hastings/work/irods/irods-externals/elasticlient0.1.0_src/elasticlient/external/httpmockserver/external/cpr/cpr/error.cpp:25:14: note: previous case defined here
        case CURLE_PEER_FAILED_VERIFICATION:
             ^
1 error generated.
```

From libs3.log
```
make[1]: Leaving directory '/home/hastings/work/irods/irods-externals/libs359b62371-0_src/libs3'
INFO -   stderr: src/request.c: In function ‘request_curl_code_to_status’:
src/request.c:1871:5: error: duplicate case value
     case CURLE_SSL_CACERT:
     ^~~~
src/request.c:1870:5: note: previously used here
     case CURLE_PEER_FAILED_VERIFICATION:
     ^~~~
make[1]: *** [GNUmakefile:217: build/obj/request.do] Error 1
make[1]: *** Waiting for unfinished jobs....
src/request.c: In function ‘request_curl_code_to_status’:
src/request.c:1871:5: error: duplicate case value
     case CURLE_SSL_CACERT:
     ^~~~
src/request.c:1870:5: note: previously used here
     case CURLE_PEER_FAILED_VERIFICATION:
     ^~~~
make[1]: *** [GNUmakefile:209: build/obj/request.o] Error 1
INFO - 
ERROR - build failed
Building [libs3]
```

 Checking the libcurl changelog we can see that CURLE_SSL_CACERT has indeed been deprecated.

```
- [Han Han brought this change]

  ssl: deprecate CURLE_SSL_CACERT in favour of a unified error code
  
  Long live CURLE_PEER_FAILED_VERIFICATION
```
In was able to fix both of these by just to removing the CURLE_SSL_CACERT case the switch statement. I'm not sure what the actual solution should be for irods/externals. I've not yet looked closely at their forks within irods. Presumably these changes are already in the newer (upstream) versions of libs3 and cpr. What is the policy for bumping the versions of these packages? Should the corresponding commits be cherry picked? Should I make a pull requests with my fixes? This may not be a problem for now with older systems but it clearly is with Debian 10 and presumably it will be with Ubuntu 20.04 and CentOS 8.

As a slight aside, I think it would be very nice if irods and irods-externals allow the user to provide the required dependencies outside of the irods-externals package.

Cheers,

Nick.

**Comment by trel** [comment]
Nick,

We truly appreciate the effort of good issue descriptions.   Thanks.

Short version...

We can probably bump cpr and libs3 without too much pain, but haven't poked it because Debian10 isn't in our supported list.

Longer Version...

We have prioritized keeping all the irods/externals versions the same across supported OS/Version combinations - mostly out of limited time/attention.  Having a single source of truth has allowed us to move as fast (ahem) as we do.  Once something has worked, we've moved onto other things.

I'd be happy to have a smarter build system that did not depend on this same-version-everywhere assumption.  This would allow us to more easily support additional OS/Version combinations and allow more community involvement on the systems of their choice.  A benefit of our pinning to specific external versions everywhere, of course, is that we know things work, and we can be sure of it in public.

I believe we currently only have changes to the irods/libs3 fork - everything else we've maintained edits for over the years have been merged back into the upstream projects (cmake, boost, etc.).  The current batch of supported operating systems might all support the minimum versions necessary, we have not audited that set of tooling in a while.

I believe we'll probably continue to support CentOS7 and Ubuntu16 throughout the life of the 4-2-stable branch (this could be 4.2.9 plus one or two more releases).  4.3.0 can make a clean break (there are a few things we've been waiting to cleanly transition to... systemd, unified logging, unified configuration, newer openssl).

The biggest hurdle to letting others supply the required dependencies involves our use of the clang ecosystem (needed when gcc didn't yet support C++14 features), and shared objects (which requires, among other things, the -fPIC flag everywhere).

If iRODS can be built with mainline/available gcc again (shouldn't be too much work, famous last words), we can probably remove the need for most of the externals to be built by us.

**Comment by sprinkjm** [comment]
+1 for this. The fix seems to be in for other folks w/ this problem to have an #ifdef for the version of curl from ~2 yrs ago, see https://github.com/whoshuu/cpr/blob/v1.5.2_pre/cpr/error.cpp (which is a prerelease branch from the cpr dependency of elasticlient).

**Comment by trel** [comment]
We have recently rebased https://github.com/irods/libs3 atop its upstream (https://github.com/bji/libs3)

Will look again at cpr before too long - in the run-up to 4.3.0, we'll get everything up to date again.

**Comment by SwooshyCueb** [comment]
cpr and libs3 have been removed from externals.
